### ISSUE TITLE
VNC/Logs disconnect/reconnect every few seconds

### ISSUE THREAD

**Issue by aluitink** [aerokube/ggr-ui#24]
Hello,
I've set up a 3 node cluster and I'm trying to use ggr-ui to aggregate the VNC/Logs into a single Selenoid-UI.

The individual Selenoid-UI instances work great, but if I try to view the aggregate view, the VNC/Logs are connected/reconnected over and over again.

Seeing Connection closed (code: 1000) on the WS session in Dev tools and remote Selenoid logs show connect/disconnect of VNC/Log sessions.

**Comment by vania-pooh** [comment]
@aluitink what's inside GGR UI logs?

**Comment by aluitink** [comment]
Just these lines cycling over and over.

> [WEBSOCKET] [New connection] [10.1.17.97]
> [WEBSOCKET] [Starting websocket session to ws://10.1.17.115:4444/logs/656ea92e8412f950947da1fcf5736850] [10.1.17.97]
> [WEBSOCKET] [Client disconnected: ws://10.1.17.115:4444/logs/656ea92e8412f950947da1fcf5736850] [10.1.17.97]
> [WEBSOCKET] [Closed websocket session to ws://10.1.17.115:4444/logs/656ea92e8412f950947da1fcf5736850] [10.1.17.97]
> [WEBSOCKET] [New connection] [10.1.17.97]
> [WEBSOCKET] [Starting websocket session to ws://10.1.17.115:4444/vnc/656ea92e8412f950947da1fcf5736850] [10.1.17.97]
> [WEBSOCKET] [Client disconnected: ws://10.1.17.115:4444/vnc/656ea92e8412f950947da1fcf5736850] [10.1.17.97]
> [WEBSOCKET] [Closed websocket session to ws://10.1.17.115:4444/vnc/656ea92e8412f950947da1fcf5736850] [10.1.17.97]
> [WEBSOCKET] [New connection] [10.1.17.97]
> [WEBSOCKET] [Starting websocket session to ws://10.1.17.115:4444/logs/656ea92e8412f950947da1fcf5736850] [10.1.17.97]
> [WEBSOCKET] [Client disconnected: ws://10.1.17.115:4444/logs/656ea92e8412f950947da1fcf5736850] [10.1.17.97]
> [WEBSOCKET] [Closed websocket session to ws://10.1.17.115:4444/logs/656ea92e8412f950947da1fcf5736850] [10.1.17.97]
> 
> >

**Comment by vania-pooh** [comment]
@aluitink that's confirmed to be a bug and will be fixed in next release.
