### ISSUE TITLE
Viewing using VNC does not always work through the ggr-ui

### ISSUE THREAD

**Issue by linkinek** [aerokube/ggr-ui#26]
Иногда не возможно просмотреть браузер через VNC через ggr-ui. При этом через selenoid-ui всё в порядке.
Используется версия 1.1.0

![image](https://user-images.githubusercontent.com/14567888/41144265-6801ddb0-6b0d-11e8-8cc2-9c26ddf652d3.png)

**Comment by vania-pooh** [comment]
И давайте хотя бы тикет на английском заводить. Я уже молчу про чатик.

**Comment by vania-pooh** [comment]
@linkinek please try with https://github.com/aerokube/ggr-ui/releases/tag/1.1.1.

**Comment by linkinek** [comment]
@vania-pooh In version 1.1.1 works.

**Comment by vania-pooh** [comment]
@linkinek closing then?

**Comment by linkinek** [comment]
@vania-pooh yes.
