### ISSUE TITLE
selenoid-ui fails to get ggr-ui status

### ISSUE THREAD

**Issue by rab2215** [aerokube/ggr-ui#27]
When setting up ggr > ggr-ui > selenoid-ui using docker-compose, selenoid-ui fails to get the status from ggr-ui.  If I access the ggr-ui /status API directly, i get the response as expected.

Repeating Error:

> selenoid-ui_1  | 2018/06/18 20:09:49 can't get status (Get http://ggrui:8888/status: context deadline exceeded)

docker-compose file:

> version: '3'
services:
  ggr:
    restart: always
    image: aerokube/ggr
    ports:
          - "4444:4444"
    volumes:
      - "./:/etc/grid-router:ro"
    command: ["-quotaDir", "/etc/grid-router"]
  ggr-ui:
    restart: always
    image: aerokube/ggr-ui
    ports:
      - "8888:8888"
    volumes:
      - "./:/etc/grid-router/quota:ro"
  selenoid-ui:
    restart: always
    image: aerokube/selenoid-ui
    links:
      - ggr-ui
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://ggr-ui:8888"]

I have used the same docker-compose configuration with base selenoid > selenoid-ui with no issues.  Any ideas as to whats causing this?

**Comment by vania-pooh** [comment]
@rab2215 from the code point of view both Selenoid and Ggr UI are identical. The only difference is the port. You could try to link them manually and see whether it helps. I think this is something related to custom Docker networks and respective iptables rules.

**Comment by vania-pooh** [comment]
@rab2215 btw, are you using the latest release?

**Comment by rab2215** [comment]
Yes, I only started using ggr-ui yesterday, I also deleted all local images
and redownloaded this morning.

**Comment by benzman81** [comment]
I seem to have the same issue starting the docker images manually like this:
`docker run --name=selenium-grid-ggr -d --restart=on-failure:3 -p 54444:4444 -v ${WORKSPACE}/selenium-grid-ggr:/etc/grid-router:ro aerokube/ggr:1.5.5`

`docker run --name=selenium-grid-ggr-ui -d --restart=on-failure:3 -p 54445:8888 -v ${WORKSPACE}/selenium-grid-ggr/quota:/etc/grid-router/quota:ro aerokube/ggr-ui:1.1.1`

`docker run --name=selenium-grid-selenoid-ui -d --restart=on-failure:3 -p 54446:8080 aerokube/selenoid-ui:1.6.1 --selenoid-uri http://localhost:54445`

Any idea?

**Comment by vania-pooh** [comment]
@benzman81 guys, you surprize me. Every container has its own isolated `localhost` and this is why it is not working. You should link containers like this:
```
$ docker run --name=selenium-grid-ggr-ui -d --restart=on-failure:3 -v ${WORKSPACE}/selenium-grid-ggr/quota:/etc/grid-router/quota:ro aerokube/ggr-ui:1.1.1
$ docker run --name=selenium-grid-selenoid-ui -d --restart=on-failure:3 --link selenium-grid-ggr-ui  -p 54446:8080 aerokube/selenoid-ui:1.6.1 --selenoid-uri http://selenium-grid-ggr-ui:8888
```

**Comment by benzman81** [comment]
@vania-pooh missed that as I am pretty new to docker. Works now for me.
