### ISSUE TITLE
Unable to connect to selenoid-ui , although test runs fine

### ISSUE THREAD

**Issue by rohitpatwari84** [aerokube/ggr-ui#32]
I am sure I am missing something , but dont know what . **I am able to run my tests fine but cant see status on selenoid ui** ..Seems ggr ui is unable to connect to selenoid.

**This is my quota file -**
```
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="firefox" defaultVersion="45.0">
    <version number="58.0">
        <region name="1">
            <host name="localhost" port="4445" count="1"/>
        </region>
    </version>
</browser>
</qa:browsers>
```

**My docker-compose looks like this--**
version: '3'
 services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "/etc/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/selenoid/video:/opt/selenoid/video"
      - "./logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
     #"-video-output-dir", "/opt/selenoid/video",
    command: ["-conf", "/etc/selenoid/browsers.json","-video-output-dir", "/opt/selenoid/video","-log-output-dir","/opt/selenoid/logs","-timeout","3m","sessionTimeout","2m"]
    ports:
      - "4445:4444"
  ggr-ui:
    image: "aerokube/ggr-ui:latest-release"
    network_mode: bridge
    ports:
      - "8888:8888"
    volumes:
     - "/etc/grid-router/quota:/etc/grid-router/quota:ro"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - ggr-ui

    ports:
      - "9090:8080"
    environment:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
      command: ["--selenoid-uri", "http://ggr-ui:8888"]

**Comment by aandryashin** [comment]
Is your quota file empty?

сб, 8 сент. 2018 г., 14:33 rohitpatwari84 <notifications@github.com>:

**Comment by rohitpatwari84** [comment]
No I have pasted the contents ..Here its is  --

```
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="firefox" defaultVersion="45.0">
    <version number="58.0">
        <region name="1">
            <host name="localhost" port="4445" count="1"/>
        </region>
    </version>
</browser>
</qa:browsers>
```

**Comment by aandryashin** [comment]
localhost means containers localhost, you have to use host ip, host name,
or use network mode host...

сб, 8 сент. 2018 г., 14:53 rohitpatwari84 <notifications@github.com>:

**Comment by rohitpatwari84** [comment]
ahh..I tried that earlier..but I was appending http://<host IP> . So after removing http , it worked .
Thanks @aandryashin  (Alex) !!!
