### ISSUE TITLE
Status: invalid character 'T'

### ISSUE THREAD

**Issue by jsa34** [aerokube/ggr-ui#42]
Hello!

Something seems to be silently failing/throwing errors, but hadn't noticed until I looked in the GGR-UI logs for the docker container.

Log has numerous entries of the following:
2019/03/13 10:17:37 [STATUS] [Failed to parse response: invalid character 'T' looking for beginning of value]

Not sure what is happening.

Many thanks

**Comment by vania-pooh** [comment]
@jsa34 ggr-ui expects remote hosts to have JSON `/status` API. In your case another output is returned (probably HTML or XML).

**Comment by jsa34** [comment]
Aha - this is probably related to https://github.com/aerokube/ggr/issues/274.

Thank you!
