### ISSUE TITLE
Do not take into consideration not running Selenoid instances behind ggr-ui

### ISSUE THREAD

**Issue by slipwalker** [aerokube/ggr-ui#5]
Currently, if there are no running Selenoid instances behind ggr (or almost all of them are down), it takes a while until /status request gets resolved with some response. It's a bit inconvenient. Would be good to have some mechanism to sort these not running instances out and do not consider them in order to have more fast ggr-ui request-response logic. Once instance becomes available, it should be considered then. Any other suggestions to improve this would be appreciated.

**Comment by vania-pooh** [comment]
Seems to be a reasonable idea.

**Comment by vania-pooh** [comment]
We fixed this by adding `-response-time` flag and parallel polling. Should not reproduce in release `1.1.0`.
