### ISSUE TITLE
Can you add a screenshot of the UI in the README.md ?

### ISSUE THREAD

**Issue by djangofan** [aerokube/ggr-ui#57]
Can you add a screenshot of the UI in the README.md ?

**Comment by vania-pooh** [comment]
@djangofan this name `ggr-ui` is a bit confusing as in fact it is a **backend** application working in conjunction with regular Selenoid UI and delivering the same `/status` API that allows Selenoid UI to interact with Selenoid but for a collection of Selenoid instances.
