### ISSUE TITLE
Give name to selenoid backend

### ISSUE THREAD

**Issue by Pavel077** [aerokube/ggr-ui#60]
Hello.

We are using ggr-ui with two selenoid backends.
In ggr-ui status page one backend is named "test" and another "unknown".
I have no idea where ggr got these names for them.

The quota file  `test.xml` describes selenoid servers like this:
```
<host name="192.168.34.91" port="4444" count="50"/>
<host name="192.168.131.2" port="4444" count="35"/>
```

How can we set names for backend servers defined in quota file?
Thanks!

![Screenshot 2021-07-19 161940](https://user-images.githubusercontent.com/13832547/126166692-61e2925b-35a3-465c-bc2f-9ad1dc5cdcd7.jpg)

**Comment by vania-pooh** [comment]
@Pavel077 there are not backend names but basic HTTP auth user names being used in Selenium URL.

**Comment by Pavel077** [comment]
Thank you!
